# CALLING SPEC:
# - Purpose: synchronize human-usable CLI auth/bootstrap files into the per-user workspace container.
# - Inputs: callers that import `backend/services/workspace_cli_env.py` and pass user/session context.
# - Outputs: helper functions for refreshing workspace CLI config files.
# - Side effects: Docker exec into the user's running workspace container and file writes inside that container.
from __future__ import annotations

from backend.config import Settings, get_settings
from backend.services import docker_cli
from backend.services.agent_workspace import build_user_workspace_spec

_WORKSPACE_ROOT = "/workspace/scratch"
_DATA_ROOT = "/workspace/uploads"
_CONFIG_PATH = "/workspace/.ide/bh-env.json"
_SHELL_PATH = "/workspace/.ide/bh-shell-env.sh"
_BASHRC_PATH = "/home/app/.bashrc"


def refresh_workspace_cli_env(
    *,
    user_id: str,
    session_token: str,
    settings: Settings | None = None,
) -> None:
    resolved_settings = settings or get_settings()
    spec = build_user_workspace_spec(user_id=user_id, settings=resolved_settings)
    docker_cli.exec_in_container(
        docker_binary=spec.docker_binary,
        container_name=spec.container_name,
        env={
            "BH_API_BASE_URL": resolved_settings.workspace_backend_base_url,
            "BH_AUTH_TOKEN": session_token,
            "BH_WORKSPACE_ROOT": _WORKSPACE_ROOT,
            "BH_DATA_ROOT": _DATA_ROOT,
            "BH_CONFIG_PATH": _CONFIG_PATH,
            "BH_SHELL_PATH": _SHELL_PATH,
            "BH_BASHRC_PATH": _BASHRC_PATH,
        },
        command=["python", "-c", _WRITE_WORKSPACE_CLI_ENV_SCRIPT],
    )


_WRITE_WORKSPACE_CLI_ENV_SCRIPT = """
import json
import os
from pathlib import Path

config_path = Path(os.environ["BH_CONFIG_PATH"])
shell_path = Path(os.environ["BH_SHELL_PATH"])
bashrc_path = Path(os.environ["BH_BASHRC_PATH"])
config_path.parent.mkdir(parents=True, exist_ok=True)

payload = {
    "api_base_url": os.environ["BH_API_BASE_URL"],
    "auth_token": os.environ["BH_AUTH_TOKEN"],
    "workspace_root": os.environ["BH_WORKSPACE_ROOT"],
    "data_root": os.environ["BH_DATA_ROOT"],
}
config_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\\n", encoding="utf-8")
config_path.chmod(0o600)

shell_lines = [
    "# Generated by Bill Helper workspace IDE session bootstrap.",
    f"export BH_API_BASE_URL={json.dumps(os.environ['BH_API_BASE_URL'])}",
    f"export BH_AUTH_TOKEN={json.dumps(os.environ['BH_AUTH_TOKEN'])}",
    f"export BH_WORKSPACE_ROOT={json.dumps(os.environ['BH_WORKSPACE_ROOT'])}",
    f"export BH_DATA_ROOT={json.dumps(os.environ['BH_DATA_ROOT'])}",
    "",
]
shell_path.write_text("\\n".join(shell_lines), encoding="utf-8")
shell_path.chmod(0o600)

source_line = f'[ -f "{shell_path.as_posix()}" ] && . "{shell_path.as_posix()}"'
existing = ""
if bashrc_path.exists():
    existing = bashrc_path.read_text(encoding="utf-8")
if source_line not in existing:
    prefix = "" if not existing or existing.endswith("\\n") else "\\n"
    bashrc_path.write_text(existing + prefix + source_line + "\\n", encoding="utf-8")
"""
