#!/usr/bin/env python3
# CALLING SPEC:
# - Purpose: render a fully expanded agent system prompt snapshot for committed docs.
# - Inputs: CLI args for output path, surface, date, and timezone.
# - Outputs: writes a markdown snapshot doc to disk and prints the output path.
# - Side effects: writes one markdown file; does not read the database.
from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

from backend.services.agent.prompts import SystemPromptContext, system_prompt

# Placeholders for git-tracked snapshot output. Never embed DB-derived user context.
SNAPSHOT_OMITTED = "<omitted>"
_AGENT_MEMORY_INTRO = (
    "Treat the following as persistent user-provided background and preferences.\n"
    "Follow it when it does not conflict with the rules above."
)


@dataclass(frozen=True, slots=True)
class RenderInputs:
    response_surface: str
    current_date: date
    timezone_name: str
    rendered_prompt: str


def _default_output_path() -> Path:
    return Path("docs/features/system_prompt_example.md")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render the current agent system prompt to a markdown snapshot doc.")
    parser.add_argument("--surface", default="app", help="Response surface to render. Defaults to app.")
    parser.add_argument(
        "--date",
        dest="date_text",
        default=None,
        help="Current date to inject in YYYY-MM-DD format. Defaults to today in local time.",
    )
    parser.add_argument(
        "--timezone",
        default="America/Toronto",
        help="Timezone name to inject. Defaults to America/Toronto.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output markdown path. Defaults to docs/features/system_prompt_example.md",
    )
    return parser.parse_args()


def _resolve_date(date_text: str | None) -> date:
    if date_text is None:
        return datetime.now().date()
    return date.fromisoformat(date_text)


def _load_render_inputs(*, current_date: date, timezone_name: str, response_surface: str) -> RenderInputs:
    rendered_prompt = _render_snapshot_system_prompt(
        current_date=current_date,
        timezone_name=timezone_name,
        response_surface=response_surface,
    )
    return RenderInputs(
        response_surface=response_surface,
        current_date=current_date,
        timezone_name=timezone_name,
        rendered_prompt=rendered_prompt,
    )


def _render_snapshot_system_prompt(
    *,
    current_date: date,
    timezone_name: str,
    response_surface: str,
) -> str:
    rendered_prompt = system_prompt(
        SystemPromptContext(
            current_user_context=SNAPSHOT_OMITTED,
            entity_category_context=SNAPSHOT_OMITTED,
            user_memory=None,
            current_date=current_date,
            current_timezone=timezone_name,
            response_surface=response_surface,
        )
    )
    return _replace_agent_memory_body(rendered_prompt)


def _replace_agent_memory_body(rendered_prompt: str) -> str:
    marker = f"### Agent Memory\n{_AGENT_MEMORY_INTRO}\n"
    if marker not in rendered_prompt:
        return rendered_prompt
    prefix = rendered_prompt[: rendered_prompt.index(marker) + len(marker)]
    return f"{prefix}{SNAPSHOT_OMITTED}\n"


def _build_snapshot_markdown(inputs: RenderInputs) -> str:
    markdown = (
        "# Rendered Agent System Prompt Snapshot\n\n"
        "**Do not edit this file by hand.** It is overwritten by "
        "`scripts/render_agent_system_prompt_snapshot.py`. Regenerate with "
        "`uv run python scripts/render_agent_system_prompt_snapshot.py`. "
        "Canonical prompt sources: `backend/services/agent/system_prompt.j2`, "
        "`backend/services/agent/prompt_includes/`, and "
        "`backend/services/agent/prompts.py`; the embedded `bh` cheat sheet comes from "
        "`backend/cli/reference.py`.\n\n"
        f"This doc snapshots the fully rendered agent system prompt for the "
        f"`{inputs.response_surface}` response surface on `{inputs.current_date.isoformat()}`.\n\n"
        "It is a rendered snapshot, not the canonical source of truth for prompt text.\n\n"
        "Rendered with:\n"
        f"- response surface: `{inputs.response_surface}`\n"
        f"- timezone: `{inputs.timezone_name}`\n"
        f"- current date: `{inputs.current_date.isoformat()}`\n"
        "- entity category context: placeholder `<omitted>` (not loaded from the local database)\n"
        "- account context: placeholder `<omitted>` (not loaded from the local database)\n"
        "- agent memory: placeholder `<omitted>` (not loaded from the local database)\n\n"
        "```md\n"
        f"{inputs.rendered_prompt}"
        "```\n"
    )
    return "\n".join(line.rstrip() for line in markdown.splitlines()).rstrip() + "\n"


def main() -> int:
    args = _parse_args()
    current_date = _resolve_date(args.date_text)
    output_path = Path(args.output) if args.output is not None else _default_output_path()
    inputs = _load_render_inputs(
        current_date=current_date,
        timezone_name=args.timezone,
        response_surface=args.surface,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_build_snapshot_markdown(inputs), encoding="utf-8")
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
